### ISSUE TITLE
Build Fails with Buffer.js Error

### ISSUE THREAD

**Issue by ghost** [sparksuite/simplemde-markdown-editor#160]
When I try to build this with your gulpfile, the scripts build fails with the following:

```
buffer.js:167
  throw new TypeError('must start with number, buffer, array or string');
  ^

TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:167:9)
    at new Buffer (buffer.js:58:10)
    at Concat.add (/Users/vincek/Code/markdown/node_modules/simplemde/node_modules/gulp-header/node_modules/concat-with-sourcemaps/index.js:40:15)
    at DestroyableTransform.TransformStream [as _transform] (/Users/vincek/Code/markdown/node_modules/simplemde/node_modules/gulp-header/index.js:49:12)
    at DestroyableTransform.Transform._read (/Users/vincek/Code/markdown/node_modules/simplemde/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/vincek/Code/markdown/node_modules/simplemde/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/vincek/Code/markdown/node_modules/simplemde/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:333:12)
    at writeOrBuffer (/Users/vincek/Code/markdown/node_modules/simplemde/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:319:5)
    at DestroyableTransform.Writable.write (/Users/vincek/Code/markdown/node_modules/simplemde/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:246:11)
    at write (/Users/vincek/Code/markdown/node_modules/simplemde/node_modules/vinyl-source-stream/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
```

Any ideas on why? Am I missing a node module or something?

Thanks.

**Comment by WesCossick** [comment]
You must be using node version 4 or greater. One of the dependencies in the build process does not support version 4 or greater. Track the issue here: https://github.com/tracker1/gulp-header/issues/23#issuecomment-153481340

**Comment by ghost** [comment]
This can be easily resolved by piping to vinyl-buffer before piping to header.

``` js
buffer = require("vinyl-buffer"),
...

gulp.task("browserify:dev", ["lint"], function() {
    return taskBrowserify({debug:true, standalone:"SimpleMDE"})
        .pipe(source("simplemde.debug.js"))
        .pipe(buffer())
        .pipe(header(banner, {pkg: pkg}))
        .pipe(gulp.dest("./debug/"));
});

gulp.task("browserify:min", ["lint"], function() {
    return taskBrowserify({standalone:"SimpleMDE"})
        .pipe(source("simplemde.js"))
        .pipe(buffer())
        .pipe(header(banner, {pkg: pkg}))
        .pipe(gulp.dest("./debug/"));
});
```

This resolved the issue on node v4.2.2 I didn't test it on 5.0.0 but it should work.

Should I submit a pull request?

**Comment by WesCossick** [comment]
I'd like to wait to see if the source problem is fixed before applying a bandaid. If the problem doesn't get resolved within a week or two, you can submit a PR with this workaround.

**Comment by WesCossick** [comment]
This issue has been fixed with the latest release.
