### ISSUE TITLE
when i build simplemde, i get the error,as below.

### ISSUE THREAD

**Issue by rdongxie** [sparksuite/simplemde-markdown-editor#192]
## Node version is 4.2.3

buffer.js:167
  throw new TypeError('must start with number, buffer, array or string');
  ^

TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:167:9)
    at new Buffer (buffer.js:58:10)
    at Concat.add (E:\webstorm_workspace\editor\simplemde-markdown-editor\node_m
odules\gulp-header\node_modules\concat-with-sourcemaps\index.js:40:15)
    at DestroyableTransform.TransformStream [as _transform](E:webstorm_workspa
ceeditorsimplemde-markdown-editornode_modulesgulp-headerindex.js:49:12)
    at DestroyableTransform.Transform._read (E:\webstorm_workspace\editor\simple
mde-markdown-editor\node_modules\gulp-header\node_modules\through2\node_modules\
readable-stream\lib_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (E:\webstorm_workspace\editor\simpl
emde-markdown-editor\node_modules\gulp-header\node_modules\through2\node_modules
\readable-stream\lib_stream_transform.js:160:12)
    at doWrite (E:\webstorm_workspace\editor\simplemde-markdown-editor\node_modu
les\gulp-header\node_modules\through2\node_modules\readable-stream\lib_stream_w
ritable.js:333:12)
    at writeOrBuffer (E:\webstorm_workspace\editor\simplemde-markdown-editor\nod
e_modules\gulp-header\node_modules\through2\node_modules\readable-stream\lib_st
ream_writable.js:319:5)
    at DestroyableTransform.Writable.write (E:\webstorm_workspace\editor\simplem
de-markdown-editor\node_modules\gulp-header\node_modules\through2\node_modules\r
eadable-stream\lib_stream_writable.js:246:11)
    at write (E:\webstorm_workspace\editor\simplemde-markdown-editor\node_module
s\vinyl-source-stream\node_modules\through2\node_modules\readable-stream\lib_st
ream_readable.js:623:24)

**Comment by WesCossick** [comment]
To fix this, I'll need more information. Please provide exact steps to reproduce this error (the exact console commands you've used to download and build SimpleMDE), along with your OS version, Node.js version and NPM version.

**Comment by rdongxie** [comment]
OK,
after git clone , 
step 1: npm install
step 2: gulp
then i got the error,
OS is windows 7
node.js is v4.2.3
npm is 2.14.7

**Comment by rdongxie** [comment]
same with #160

**Comment by WesCossick** [comment]
Fixed in the latest release.
