### ISSUE TITLE
Error when installing from npm

### ISSUE THREAD

**Issue by newsomc** [sparksuite/simplemde-markdown-editor#250]
When I attempt to install this project with npm I get the following error:

``` javascript
npm http GET https://registry.npmjs.org/codemirror-spell-checker
npm ERR! Error: No compatible version found: codemirror@'codemirror/CodeMirror'
npm ERR! Valid install targets:
npm ERR! ["2.33.0","3.14.1","3.15.0","3.16.0","3.17.0","3.18.0","3.19.0","3.20.0","3.21.0","3.22.0","3.23.0","4.0.3","3.24.0","4.1.0","4.2.0","4.3.0","4.4.0","4.5.0","4.6.0","4.7.0","4.8.0","4.9.0","4.10.0","4.11.0","4.12.0","4.13.0","5.0.0","5.1.0","5.2.0","5.3.0","5.4.0","5.5.0","5.6.0","5.7.0","5.8.0","5.9.0","5.10.0","5.11.0","3.11.1","3.12.0","3.13.0"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-62-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /opt/food52
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm http 404 https://registry.npmjs.org/codemirror-spell-checker
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-62-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /opt/food52
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/food52/npm-debug.log
npm ERR! not ok code 0
```

**Comment by WesCossick** [comment]
Can you provide...
1. The full, exact command you used to attempt to install
2. Your NPM version
3. Your Node.js version
4. What OS you're running this on

**Comment by newsomc** [comment]
1. The full, exact command you used to attempt to install
   `npm install`
2. NPM version
   `1.3.10`
3. Node.js version
   `v0.10.25`
4. OS

```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty
```

**Comment by newsomc** [comment]
This issue can be closed. I was running on really outdated versions. I am getting a new error which I will open a new issue for.
