### ISSUE TITLE
.eslintrc not included when downloading via bower

### ISSUE THREAD

**Issue by thomaswardiii** [sparksuite/simplemde-markdown-editor#420]
I recently attempted to include SimpleMDE via a bower install and then run gulp to compile it. I am doing this to use it as part of a Laravel Elixir build. However after attempting to build SimpleMDE with gulp, eslint complains:

```
[16:53:53] Using gulpfile ~/Code/example.com/vendor/bower_components/simplemde/gulpfile.js
[16:53:53] Starting 'prettify-js'...
[16:53:53] Starting 'prettify-css'...
[16:53:53] Finished 'prettify-js' after 217 ms
[16:53:53] Starting 'lint'...
[16:53:53] Finished 'lint' after 262 ms
[16:53:53] Starting 'browserify:debug'...
[16:53:53] Starting 'browserify'...
[16:53:53] Finished 'prettify-css' after 459 ms
[16:53:53] Starting 'styles'...
[16:53:53] gulp-debug: src/js/simplemde.js
/home/vagrant/Code/example.com/vendor/bower_components/simplemde/node_modules/eslint/lib/config.js:170
            throw noConfigError;
            ^

Error: No ESLint configuration found.
    at getLocalConfig (/home/vagrant/Code/example.com/vendor/bower_components/simplemde/node_modules/eslint/lib/config.js:162:35)
    at Config.getConfig (/home/vagrant/Code/example.com/vendor/bower_components/simplemde/node_modules/eslint/lib/config.js:256:22)
    at processText (/home/vagrant/Code/example.com/vendor/bower_components/simplemde/node_modules/eslint/lib/cli-engine.js:222:33)
    at CLIEngine.executeOnText (/home/vagrant/Code/example.com/vendor/bower_components/simplemde/node_modules/eslint/lib/cli-engine.js:749:26)
    at verify (/home/vagrant/Code/example.com/vendor/bower_components/simplemde/node_modules/gulp-eslint/index.js:20:25)
    at Transform._transform (/home/vagrant/Code/example.com/vendor/bower_components/simplemde/node_modules/gulp-eslint/index.js:70:17)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
```

My fix for this was to download the .eslintrc file from the repo and try gulp again. I'm guessing somehow this file is being ignored by the bower repository?

**Comment by WesCossick** [comment]
Can you list the files that are downloaded by bower?

**Comment by thomaswardiii** [comment]
Doing a `bower install simplemde --save -VV` I get this:

```
bower simplemde#*           not-cached https://github.com/NextStepWebs/simplemde-markdown-editor.git#*
bower simplemde#*              resolve https://github.com/NextStepWebs/simplemde-markdown-editor.git#*
bower simplemde#*             checkout 1.11.2
bower simplemde#*             resolved https://github.com/NextStepWebs/simplemde-markdown-editor.git#1.11.2
bower simplemde#^1.11.2        install simplemde#1.11.2
bower                          no-json No bower.json file to save to, use bower init to create one

simplemde#1.11.2 bower_components/simplemde
```

```
Thomass-MBP:sme_test tward$ find .
.
./bower_components
./bower_components/simplemde
./bower_components/simplemde/.bower.json
./bower_components/simplemde/bower.json
./bower_components/simplemde/CONTRIBUTING.md
./bower_components/simplemde/debug
./bower_components/simplemde/debug/simplemde.css
./bower_components/simplemde/debug/simplemde.debug.js
./bower_components/simplemde/debug/simplemde.js
./bower_components/simplemde/dist
./bower_components/simplemde/dist/simplemde.min.css
./bower_components/simplemde/dist/simplemde.min.js
./bower_components/simplemde/gulpfile.js
./bower_components/simplemde/LICENSE
./bower_components/simplemde/package.json
./bower_components/simplemde/README.md
./bower_components/simplemde/src
./bower_components/simplemde/src/css
./bower_components/simplemde/src/css/simplemde.css
./bower_components/simplemde/src/js
./bower_components/simplemde/src/js/codemirror
./bower_components/simplemde/src/js/codemirror/tablist.js
./bower_components/simplemde/src/js/simplemde.js
```
